### ISSUE TITLE
Official extension: gRPC Request Matching

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/ecosystem#14] opened 2023-04-21 13:31 UTC
### Proposal

gRPC is very popular in the cloud native ecosystem, and it would be nice to have support for mocking gRPC services in WireMock. There are already a few implementations in the [WireMock Ecosystem](https://github.com/wiremock/ecosystem) but no official ones The feature could be implemented as a standalone Java library but that still runs in the same JVM runtime to achieve higher performance. This s different from https://github.com/Adven27/grpc-wiremock that basically implements a standalone proxy service

## References

* Extension: https://github.com/wiremock/wiremock-grpc-extension/
* Docs: https://wiremock.org/docs/grpc/
* Demos: https://github.com/wiremock/wiremock-grpc-demos

Contributions are welcome!

### Prior work

- Standalone project: https://github.com/Adven27/grpc-wiremock , archived and probably up for adoption. 
- Rust implementation of gRPC Mocking: https://github.com/mustakimali/wiremock-grpc-rs 
- Separate grpcmock project that has similar architecure as WireMock: https://github.com/Fadelis/grpcmock
- https://microcks.io/documentation/using/grpc/

**Comment by pmirek** [comment] 2023-05-26 11:54
Any dates or plans to have it supported under standalone mode? That would be great if this is built in. The issue is that adven27's project is stuck now, so no support for further development.

**Comment by oleg-nenashev** [comment] 2023-06-09 09:39
@pmirek No dates at the moment. I actually forked @adven27's project to https://github.com/wiremock/grpc-wiremock after being unable to contact him. I think this is something that should continue, and we should definitely find a new maintainer. Would you be interested?

P.S: for this particular ticket, the vision after discussing with @tomakehurst is rather having a WireMock extension that runs within the same instance. It is a subject for prototyping and decision making, and it definitely does not block work on the current fork we have

**Comment by tomakehurst** [comment] 2023-11-06 14:59
@oleg-nenashev anything you want me to contribute here or should we close this per https://github.com/wiremock/wiremock-grpc-extension ?

**Comment by oleg-nenashev** [comment] 2023-11-08 15:02
@tomakehurst currently it is marked as preview on the road map. I would suggest finishing key bits like release automation to proper locations, ci, a bit more of docs/demos, and releasing as GA then. Ultimately we just give it some time to get feedback and address issues reported by users

**Comment by ritchieanesco** [comment] 2024-10-15 06:17
any more updates on this?

**Comment by tomakehurst** [comment] 2024-10-15 11:48
The gRPC extension has been GA for a while @ritchieanesco: https://github.com/wiremock/wiremock-grpc-extension

**Closed by tomakehurst** 2024-10-15 11:48 UTC
Labels: enhancement
